### ISSUE TITLE
Zero-Shot 3D Object Detection

### ISSUE THREAD

**Issue by ndkhanh360** [Yebulabula/OpenDlign#3]
Dear author,

Congratulations on your acceptance to NeurIPS! I am particularly interested in the Zero-Shot 3D Object Detection experiment in the paper. Could you please provide the code or instructions on how to modify [3DETR code](https://github.com/facebookresearch/3detr) for the experiment?

I would greatly appreciate your help and look forward to hearing from you.

Best regards,

**Comment by Yebulabula** [comment]
Dear @ndkhanh360,

We strictly follow the pipeline of PointCLIP v2 for 3D zero-shot detection. You can find more details in the paper: [PointCLIP V2: Prompting CLIP and GPT for Powerful 3D Open-world Understanding](https://openaccess.thecvf.com/content/ICCV2023/papers/Zhu_PointCLIP_V2_Prompting_CLIP_and_GPT_for_Powerful_3D_Open-world_ICCV_2023_paper.pdf).

In particular, we utilize a pretrained 3DETR model to generate 3D bounding boxes and then apply OpenDlign to classify the points within each box.

Best regards,
Ye Mao
